# Generated by Django 6.0.5 on 2026-05-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplomacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('planet', 'Planet Profile'), ('species', 'Species Database'), ('technology', 'Technology'), ('history', 'Historical Record'), ('threat', 'Threat Assessment'), ('organization', 'Organization'), ('event', 'Notable Event'), ('other', 'Other')], default='other', max_length=20)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('classified', 'Classified'), ('top_secret', 'Top Secret')], default='restricted', max_length=20)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_factions', models.ManyToManyField(blank=True, to='diplomacy.faction')),
                ('related_planets', models.ManyToManyField(blank=True, to='diplomacy.planet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('revised_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, max_length=300)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='intel.article')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revised_at'],
            },
        ),
    ]
