# Generated by Django 6.0.5 on 2026-05-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('homeworld', models.CharField(blank=True, max_length=200)),
                ('government', models.CharField(choices=[('republic', 'Republic'), ('empire', 'Empire'), ('theocracy', 'Theocracy'), ('oligarchy', 'Oligarchy'), ('corporate', 'Corporate State'), ('hive', 'Hive Mind'), ('anarchy', 'Anarchic'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('technology', models.CharField(choices=[('primitive', 'Primitive'), ('industrial', 'Industrial'), ('spacefaring', 'Spacefaring'), ('advanced', 'Advanced'), ('ancient', 'Ancient'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('culture_notes', models.TextField(blank=True)),
                ('known_allies', models.CharField(blank=True, max_length=500)),
                ('known_enemies', models.CharField(blank=True, max_length=500)),
                ('symbol', models.ImageField(blank=True, upload_to='factions/')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sector', models.CharField(blank=True, max_length=200)),
                ('climate', models.CharField(choices=[('temperate', 'Temperate'), ('arid', 'Arid'), ('frozen', 'Frozen'), ('jungle', 'Jungle'), ('ocean', 'Ocean'), ('volcanic', 'Volcanic'), ('gas_giant', 'Gas Giant'), ('barren', 'Barren'), ('artificial', 'Artificial')], default='temperate', max_length=20)),
                ('resources', models.CharField(choices=[('mineral', 'Mineral Rich'), ('agricultural', 'Agricultural'), ('technological', 'Technological'), ('cultural', 'Cultural'), ('strategic', 'Strategic Location'), ('energy', 'Energy Rich'), ('none', 'None / Depleted')], default='none', max_length=20)),
                ('population', models.CharField(blank=True, help_text='Estimated population', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('points_of_interest', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='planets/')),
                ('x_coord', models.FloatField(blank=True, default=0)),
                ('y_coord', models.FloatField(blank=True, default=0)),
                ('controlling_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planets', to='diplomacy.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('hostile', 'Hostile'), ('unfriendly', 'Unfriendly'), ('neutral', 'Neutral'), ('friendly', 'Friendly'), ('allied', 'Allied')], default='neutral', max_length=20)),
                ('trend', models.CharField(blank=True, help_text='e.g. Improving, Deteriorating, Stable', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('trade_active', models.BooleanField(default=False)),
                ('military_treaty', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='diplomacy.faction')),
            ],
            options={
                'verbose_name_plural': 'Relations',
            },
        ),
        migrations.CreateModel(
            name='RelationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entry', models.TextField()),
                ('effect', models.CharField(blank=True, help_text='e.g. +1 toward Friendly', max_length=100)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diplomacy.relation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
