# Generated by Django 6.0.5 on 2026-05-08 19:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('defense', models.PositiveSmallIntegerField(default=0)),
                ('soak', models.PositiveSmallIntegerField(default=0)),
                ('encumbrance', models.PositiveSmallIntegerField(default=1)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('rarity', models.PositiveSmallIntegerField(default=0)),
                ('special', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Armor',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('encumbrance', models.PositiveSmallIntegerField(default=1)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('rarity', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('characteristic', models.CharField(choices=[('brawn', 'Brawn'), ('agility', 'Agility'), ('intellect', 'Intellect'), ('cunning', 'Cunning'), ('willpower', 'Willpower'), ('presence', 'Presence')], max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('combat', 'Combat'), ('knowledge', 'Knowledge')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('homeworld', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('typical_characteristics', models.CharField(blank=True, help_text='e.g. +1 Intellect, +1 Willpower', max_length=200)),
                ('special_abilities', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('activation', models.CharField(blank=True, help_text='Passive, Active (Incident), etc.', max_length=100)),
            ],
            options={
                'ordering': ['name', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('skill', models.CharField(blank=True, help_text='e.g. Ranged (Light), Gunnery', max_length=100)),
                ('damage', models.PositiveSmallIntegerField(default=0)),
                ('crit', models.PositiveSmallIntegerField(default=3, help_text='Critical rating')),
                ('range', models.CharField(blank=True, help_text='Engaged, Short, Medium, Long, Extreme', max_length=50)),
                ('special', models.CharField(blank=True, help_text='Special qualities', max_length=200)),
                ('encumbrance', models.PositiveSmallIntegerField(default=1)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('rarity', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Character name', max_length=200)),
                ('callsign', models.CharField(blank=True, max_length=100)),
                ('specializations', models.CharField(blank=True, help_text='Career specializations', max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('injured', 'Injured / Recovering'), ('mia', 'Missing in Action'), ('kia', 'Killed in Action'), ('retired', 'Retired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('portrait', models.ImageField(blank=True, upload_to='personnel/')),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('appearance', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('brawn', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('agility', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('intellect', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cunning', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('willpower', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('presence', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('wound_threshold', models.PositiveSmallIntegerField(default=10)),
                ('current_wounds', models.PositiveSmallIntegerField(default=0)),
                ('strain_threshold', models.PositiveSmallIntegerField(default=10)),
                ('current_strain', models.PositiveSmallIntegerField(default=0)),
                ('soak', models.PositiveSmallIntegerField(default=0, help_text='Brawn + armor soak')),
                ('defense_ranged', models.PositiveSmallIntegerField(default=0)),
                ('defense_melee', models.PositiveSmallIntegerField(default=0)),
                ('experience_available', models.PositiveIntegerField(default=0)),
                ('experience_total', models.PositiveIntegerField(default=0)),
                ('motivation_type', models.CharField(blank=True, help_text='e.g. Cause, Relationship, Personal', max_length=100)),
                ('motivation_description', models.TextField(blank=True)),
                ('duty', models.CharField(blank=True, help_text='What drives this agent for the Keleres', max_length=200)),
                ('credits', models.IntegerField(default=0, help_text='Universal credits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armor', models.ManyToManyField(blank=True, to='personnel.armor')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.career')),
                ('gear', models.ManyToManyField(blank=True, to='personnel.gear')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_file', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.species')),
                ('talents', models.ManyToManyField(blank=True, to='personnel.talent')),
                ('weapons', models.ManyToManyField(blank=True, to='personnel.weapon')),
            ],
            options={
                'verbose_name': 'Personnel File',
                'verbose_name_plural': 'Personnel Files',
            },
        ),
        migrations.CreateModel(
            name='PersonnelSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('is_career', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='personnel.personnelfile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.skill')),
            ],
            options={
                'verbose_name': 'Personnel Skill',
                'verbose_name_plural': 'Personnel Skills',
                'unique_together': {('personnel', 'skill')},
            },
        ),
    ]
