# Generated by Django 6.0.5 on 2026-05-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('codename', models.CharField(blank=True, help_text='Classified operation codename', max_length=100)),
                ('classification', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('classified', 'Classified'), ('top_secret', 'Top Secret')], default='classified', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='draft', max_length=20)),
                ('briefing', models.TextField(blank=True)),
                ('debrief', models.TextField(blank=True, help_text='Post-mission report')),
                ('location', models.CharField(blank=True, help_text='Planet or sector', max_length=200)),
                ('threat_level', models.CharField(blank=True, help_text='Low, Medium, High, Critical', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_personnel', models.ManyToManyField(blank=True, related_name='missions', to='personnel.personnelfile')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('is_primary', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='missions.mission')),
            ],
            options={
                'ordering': ['mission', 'order'],
            },
        ),
    ]
